version: '3.8'

services:
  # ---------------------------
  # Training service
  # ---------------------------
  training:
    build:
      context: .
      dockerfile: Dockerfile.training
    volumes:
      - ./federated_data:/app/federated_data
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow

  # ---------------------------
  # Model serving API
  # ---------------------------
  serving:
    build:
      context: .
      dockerfile: Dockerfile.serving
    ports:
      - "8000:8000"
    volumes:
      - ./federated_data:/app/model
    environment:
      - MODEL_PATH=/app/model/federated_churn_model.h5
      - PREPROCESSOR_PATH=/app/model/preprocessor.pkl
    depends_on:
      - training


  # ---------------------------
  # MLflow server
  # ---------------------------
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow/mlruns

  # ---------------------------
  # Prometheus monitoring
  # ---------------------------
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  # ---------------------------
  # Grafana monitoring dashboard
  # ---------------------------
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
