apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: churn-prediction
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    
    route:
      group_by: ['alertname', 'feature']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'drift-webhook'
      
      routes:
        - match:
            severity: critical
          receiver: 'drift-webhook'
          continue: true
    
    receivers:
      - name: 'drift-webhook'
        webhook_configs:
          - url: 'http://churn-api-service:8000/webhook/drift-alert'
            send_resolved: true
    
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'feature']